In [1]:
# Import library
import pandas as pd

In [2]:
# Load the dataframe
dataframe = pd.read_csv("../../data/df_trees.csv", sep=",", index_col=None)

In [4]:
# Check the structure of the dataframe
dataframe.head()

,Tree ID,Name,DBH (cm),Replacement Value (eur),Carbon Storage (kg),Carbon Storage (eur),Gross Carbon Sequestration (kg/yr),Gross Carbon Sequestration (eur/yr),Avoided Runoff (mcube/yr),Avoided Runoff (eur/yr),...,Total Annual Benefits (eur/yr),Oxygen Production (kg/yr),Height (m),Crown Height (m),Crown Width (m),Canopy Cover (m2),Leaf Area (m2),Leaf Biomass (kg),Latitude,Longitude
0,1,Acer pseudoplatanus,8.0,179.43,12.0,1.92,1.1,0.17,0.0,0.01,...,0.21,2.8,3.5,1.0,1.5,1.8,3.5,0.2,46.051599,11.072014
1,2,Acer pseudoplatanus,8.0,179.43,12.9,2.07,1.1,0.18,0.0,0.01,...,0.23,3.0,5.0,1.5,1.5,1.8,4.2,0.3,46.051541,11.072108
2,3,Acer pseudoplatanus,9.0,227.09,16.2,2.61,1.3,0.20,0.0,0.01,...,0.25,3.4,4.5,1.3,1.5,1.8,4.0,0.3,46.051668,11.071959
3,4,Acer pseudoplatanus,11.0,482.46,25.7,4.13,1.6,0.26,0.0,0.02,...,0.34,4.3,5.0,1.5,2.5,4.9,7.1,0.5,46.063778,11.150170
4,7,Cupressus,25.0,1110.29,448.2,72.02,11.1,1.78,0.0,0.02,...,1.85,29.5,8.0,2.4,1.5,1.8,6.6,1.5,46.052305,11.071550

In [34]:
# Count the number of occurrencies for each species
counting_species = dataframe['Name'].value_counts(sort=True).reset_index()

In [39]:
# Rename the variables
counting_species = counting_species.rename(columns={'index':'Species',
                                                     'Name':'Count'})

In [40]:
# Save the dataframe of counting species
counting_species.to_csv("../../data/counting_species.csv", sep=",", index=False)

In [41]:
# Load it to test its integrity
pd.read_csv("../../data/counting_species.csv")

                    Species  Count
0          Celtis australis   1028
1    Aesculus hippocastanum    581
2          Carpinus betulus    536
3             Tilia cordata    509
4      Platanus x hispanica    502
..                      ...    ...
219    Calocedrus decurrens      1
220          Acer tataricum      1
221   Forsythia viridissima      1
222  Forsythia x intermedia      1
223           Abies pinsapo      1

[224 rows x 2 columns]